### ISSUE TITLE
Use Pinterest API for Conversions token

### ISSUE THREAD

**Issue by alsguimaraes** [managed-components/pinterest#6]
Hi there. 
Any plans to add support for the Pinterest API for Conversions?
This would allow true zaraz server-to-server communication for Pinterest as well.

**Comment by bjesus** [comment]
It's actually coming up very soon soon as a separate MC, @ad-astra-via will update this thread once it's available

**Comment by alsguimaraes** [comment]
Hi again. Any news?
Is there something I can help with?

**Comment by kuba-orlik** [comment]
We're still working on that! Will let you know here once it's released

**Comment by kuba-orlik** [comment]
Hi @alsguimaraes, the Pinterest Conversion API is now public, thanks to @ad-astra-via's efforts. You can find it here:

https://github.com/managed-components/pinterest-conversion-api

It's not yet part of Zaraz, but it's going to be released in the near future (next week seems likely). If you're in a rush, you can use the "Custom Managed Component" tool integration in Zaraz in order to use the tool today

**Comment by alsguimaraes** [comment]
Thanks a lot.That's good news.
I will wait for it to be integrated with Zaraz.
Keep up the good work!

**Comment by kuba-orlik** [comment]
@alsguimaraes this has been merged as part of Zaraz - you can easily set it up using the Dashboard :tada:
